### ISSUE TITLE
DEFAULT_SETTINGS not getting merged with plugin.loadData()

### ISSUE THREAD

**Issue by dneez** [ohm-en/obsidian-plugin-manager#2]
Hi.
It seems that `Object.assign()` that you are using for merging `plugin.loadData()` into `DEFAULT_SETTINGS` is not doing deep-merging. That means `pluginArr` from `plugin.loadData()` will overwrite one from `DEFAULT_SETTINGS` completely.
For me, this meant not being able to activate and configure delay for plugins added after latest update.
I have temporarily done the following in local copy of plugin:
```javascript
const pluginSettings = {}
pluginSettings.pluginArr = Object.assign(
   {},
   DEFAULT_SETTINGS.pluginArr,
   (await plugin.loadData()).pluginArr
);
```
The above is not checking for presence of `pluginArr` in `plugin.loadData()`

**Comment by ohm-en** [comment]
I appreciate the report @dneez. You are correct, after pluginArr is saved once, newly installed plugins won't be able to save any settings. An oversight on my part, but I will be working on a proper fix; however, I realize this isn't the actual issue (as `DEFAULT_SETTINGS` only runs `onload`). I believe changing my listener to create entries as new ones are saved will be a more encompassing resolution. Expect a minor release by tomorrow.

**Comment by ohm-en** [comment]
@dneez, I've added a [commit](https://github.com/ohm-en/obsidian-plugin-manager/commit/48ac1fbe7a63b5ddf62c727c0d50de76129915a5#) which should fix the issue. I'll be releasing a follow up release tomorrow once I confirm functionality.

P.S.
Ignore the "test" I added. That wasn't meant for this version.

**Comment by ohm-en** [comment]
Hi @dneez,

Please confirm whether or not the v0.1.3 version release resolves your problem.

Thanks for the report :)

**Comment by dneez** [comment]
Seems to be working now.
1. Installed new plugin
2. Configured delay and enabled
3. Restarted Obsidian
4. Settings persisted
Thanks for the fix!

**Comment by markthepixel** [comment]
I cannot install, get a plugin id error

**Comment by ohm-en** [comment]
@markthepixel That should be resolved now.
