### ISSUE TITLE
"Plugin ID mismatch" when installing.

### ISSUE THREAD

**Issue by dneez** [ohm-en/obsidian-plugin-manager#3]
Hi.
I get "Plugin ID mismatch" when installing via Obsidian community plugin manager.
Works fine installing via BRAT.

**Comment by AndyLiu9** [comment]
Same here, can't install it through Obsidian

**Comment by ohm-en** [comment]
My apologies for the issue @AndyLiu9  and @dneez . A foolish mistake on my part. 

I've fixed it now, so I'd appreciate if you would confirm on your ends. I appreciate your patience.

**Comment by AndyLiu9** [comment]
Thanks, now solved!
