### ISSUE TITLE
Time input for plugins with long name/description  is not visible

### ISSUE THREAD

**Issue by mwoz123** [ohm-en/obsidian-plugin-manager#5]
Digits in input for plugins with long name/description are not visible. Purposed solution:
Input moved below on/off checkbox

Screen Resolution is
360x780

Example: roll over daily todos:

![Screenshot_20230629-075230](https://github.com/ohm-en/obsidian-plugin-manager/assets/4487025/23334f69-cf10-4726-8c28-43faa575d896)

**Comment by ohm-en** [comment]
Hey @mwoz123,

I appreciate the report. I'd noticed the issue awhile back and hadn't put much thought into it. I didn't figure I'd stop you from changing certain plugins.

Expect an update by the end of the weekend.

**Comment by ohm-en** [comment]
Hey @mwoz123,

I've made a pre-release (v0.1.6) that should fix your problem. You can install that with [BRAT](https://github.com/TfTHacker/obsidian42-brat) or wait until my full re-release of the settings menu for the plugin.

Have a good one.

**Comment by mwoz123** [comment]
Thanks I'll wait for a normal stable release;)
